name: Build Deploy QE Automation

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "================================"
          echo "Building Application..."
          sleep 5
          echo "Build Successful"
          echo "================================"

  deploy:
    name: Deploy to DEV
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "================================"
          echo "Deploying Application..."
          sleep 5
          echo "Deployment Successful"
          echo "================================"

  qe-automation:
    name: QE Automation
    needs: deploy
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify GitHub CLI
        run: gh --version

      - name: Trigger Playwright Workflow
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh workflow run playwright1.yml \
            --repo Gukapriyan/playwright-typescript-framework \
            --ref main \
            -f environment=DEV \
            -f suite=Regression

          echo "================================"
          echo "Playwright workflow triggered."
          echo "================================"
